# @package _global_
data:
  train_path: data/commonvoice_train_manifest.json
  val_path: data/commonvoice_dev_manifest.json
training:
  max_epochs: 16
  gpus: 1
  precision: half
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  accelerator: ddp
  checkpoint_callback: True
checkpoint:
  save_top_k: 1
  monitor: "wer"